# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af10c6b202170822f6c74fc3314b25dca1f3a89d47e97ae618bbce895e0f7ac5e6609a25ec7cd5e8e7be98557a14712b72de8a2d0efff0a4b2b3ec1a0151bdcd

test:
  secret_key_base: b9d1e77648d93db1fa0e5d37955259cea69c7e1261e0397b5e3e99f54a25caba2787336f5f948757ff70ecc35a29356f3cf3bd8f53ace92ffec04c239ca05beb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
